#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';


use Symfony\Component\Console\Application;
use App\Console\Commands\CreateCommand;
$app = new Application();
$app->add(new CreateCommand());
$app->run();